### ISSUE TITLE
How to run on GPU

### ISSUE THREAD

**Issue by Henry-E** [minsangkim142/R-net#17]
I'm only vaguely familiar with tensor flow and couldn't figure out how to run this on gpu. There doesn't appear to be an option for it in the params settings. The tf.set_devices appear to be explicitly cpu and should probably be left that way. And when the model ran on a gpu enabled device, it didn't use the GPU by default. The training times appeared to be the same as if it was run on a CPU. Thanks for the help

**Comment by minsangkim142** [comment]
Hi @Henry-E 
To my understanding, if you install gpu-enabled tensorflow through pip or wheel they try to automatically use available gpu (check [here](https://www.tensorflow.org/install/)). Usually you can install this via `pip install --upgrade tensorflow-gpu`. I just built the model based on the assumption that whoever wants to run the model on gpu will want to use `tensorflow-gpu` version instead of normal tensorflow.

Also on a side note, if you don't want to use gpu in a gpu-enabled version, you can run the model using this line `CUDA_VISIBLE_DEVICES=, model.py` and the model will run on cpu.

**Comment by Henry-E** [comment]
great, I must not have been using a gpu enabled version of tensor flow. And if I'm on a node with multiple GPUs then presumably it can restrict the usage by specifying `CUDA_VISIBLE_DEVICES=0, python model.py`. Thanks again
