### ISSUE TITLE
ValueError cannot reshape array

### ISSUE THREAD

**Issue by dpappas** [minsangkim142/R-net#20]
I keep getting the following error. 
What can i do about it ?
Thank you

`
Traceback (most recent call last):
  File "model.py", line 256, in <module>
    main()
  File "model.py", line 216, in main
    glove = np.reshape(glove,(Params.vocab_size,Params.emb_size))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 658805400 into shape (91604,300)
`

**Comment by minsangkim142** [comment]
Hi @dpappas, are you using your own glove word vectors? If so, you have to change this [line](https://github.com/minsangkim142/R-net/blob/dd77447fa20e8cdad65eac9f5f33f468b159c8d7/params.py#L42) to adjust your word vector size.
If you're not using your own word vectors but you're still getting this error, please make sure you're using the latest version of Spacy. 
`Params.vocab_size` must be specified so that the number of lines in your word_vectors.txt file (e.g. `glove.840B.300d.txt` has exactly `Params.vocab_size - 1` lines)

**Comment by QiXuanWang** [comment]
Interesting, I thought it was my mistake and I tried to change vocab_size to 2196018. And it turns out to be the correct behavior. I would suggest put this information somewhere in README or FAQ.

**Comment by minsangkim142** [comment]
Thanks for picking it out. I just fixed it :)

**Comment by dpappas** [comment]
Hello everyone

When you download the pretrained glove embeddings
`wget http://nlp.stanford.edu/data/glove.840B.300d.zip`
you get the entirety of the embeddings matrix with 2196018 words in the vocabulary.

Is there a case where you only kept 91604 words (perhaps after discarding any word not present in the squad corpus?).
If that is the case it would be very helpful to provide only these embeddings as the model would be less demanding in resources.

**Comment by minsangkim142** [comment]
Hi @dpappas, now instead of running 
`python process.py -process True`
please run this line instead
`python process.py --reduce_glove True --process True`

**Comment by dpappas** [comment]
Thank you very much for your immediate response!
