### ISSUE TITLE
Can we do transfer learning on R-net?

### ISSUE THREAD

**Issue by jenniferzhu** [minsangkim142/R-net#22]
i.e. how can we add new paragraphs for R-net to generate answer from in real practice? Thanks

**Comment by theSage21** [comment]
It would be nice to have a separate branch containing a simple demo page. I
can write it and maybe you could help?

**Comment by minsangkim142** [comment]
That would be awesome if you could add your own paragraphs and questions for testing. @theSage21 do you have ideas on how you would approach this? I save word2index dictionary in dictionary.pkl file which could be used to convert user input to indexes for input.
Example could be:
`>> paragraph("The Facebook AI Research (FAIR) Residency Program is a one-year research training program with Facebook’s AI Research group, designed to give you hands-on experience of machine learning research. The program will pair you with a researcher or engineer in FAIR, who will act as your mentor. Together, you will pick a research problem of mutual interest and then devise new deep learning techniques to solve it. We also encourage collaborations beyond the assigned mentor.")`
and this line could be parsed to feed the user input information to the network.
`>> How long is Facebook AI Research Residency Program?`
` one-year`
`>> etc`

**Comment by theSage21** [comment]
If we were to do this it would be nice if we had a web interface for it.
That way people can spice it according to taste. Something similar to the
bidaf demo page should be ok I guess.

I'll give it thought and action once I'm near a laptop.

On 17-Feb-2018 09:32, "Min" <notifications@github.com> wrote:

That would be awesome if you could add your own paragraphs and questions
for testing. @theSage21 <https://github.com/thesage21> do you have ideas on
how you would approach this? I save word2index dictionary in dictionary.pkl
file which could be used to convert user input to indexes for input.
Example could be:
>> paragraph("The Facebook AI Research (FAIR) Residency Program is a
one-year research training program with Facebook’s AI Research group,
designed to give you hands-on experience of machine learning research. The
program will pair you with a researcher or engineer in FAIR, who will act
as your mentor. Together, you will pick a research problem of mutual
interest and then devise new deep learning techniques to solve it. We also
encourage collaborations beyond the assigned mentor.")
and this line could be parsed to feed the user input information to the
network.
>> How long is Facebook AI Research Residency Program?
one-year
>> etc

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/minsangkim142/R-net/issues/22#issuecomment-366414478>,
or mute the thread

**Comment by theSage21** [comment]
So a very simple way of getting this done would be a new mode (maybe `demo`?) which is very close to what the `test` mode does and call the `sess.run` within an API call. This along with some simple HTML should allow a basic web based demo to work. Should I submit a PR?

**Comment by theSage21** [comment]
I'd also suggest changing the issue title to something along the line of `live evaluation/demo` since transfer learning can be misleading here.

**Comment by minsangkim142** [comment]
Yup if you have an initial idea or proof of concept of html web please submit a PR and I'll start working on it too :)

**Comment by minsangkim142** [comment]
Opened #23 Thanks everyone :)
